import type { NextPage } from "next";
import Head from "next/head";
import Body from "../stories/Body";
import Header from "../stories/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Body />
      </main>
    </div>
  );
};

export default Home;
